version: "3"

services:
  linkcutter:
    build: .
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "Password123"
    volumes:
      - ./postgress/linkcutter:/var/lib/postgresql/data
    ports:
      - "5432:5432"